version: '3.4'

services:
  playwrighttest:
    image: playwrighttest
    build:
      context: node_modules/@playwright/test
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
